highlighter: pygments

markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]

gems: [jekyll-paginate]
paginate: 7
paginate_path: "page:num"
layout: post
permalink: /:categories/:title
excerpt_separator: "[-----]"

# mode: dev
mode: product
url: https://fantasylions.github.io/
devurl: http://localhost:4000/
name: Fantasylion
title: 无用郎中 | 生命不止，奋斗不息
description: "zl.shi's personal weblog, on coding or such stuff"

my:
    displayName: fantasylion
    realName: zl.shi
    realName_cn: 施正良
    jobTitle: "Web Coder"
    contact:
        qq: 473112797
        email: lionsmail1015@gmail.com
        github: http://www.github.com/Fantasylions
        qzone: http://473112797.qzone.qq.com
        pinterest: https://www.pinterest.com/miblah/
        tel: 18394335249
        address:
            country: China
            state: ZheJiang
            city: ShangHai
            distribute: Hongshan
            postcode: 450000
            cell: "zl.shi"
    skills:
        frontend: ["HTML | Markdown", "CSS | SASS", "JS | jQuery", "Bootstrap"]
        backend: ["Java", "MySQL", "Redis", "Regex", "Laravel", "OSC"]
        tools: ["Sublime Text", "Git | Github", "Linux", "Jekyll | Liquid"]

collections:
    qqGroupGuide:
        output: true

defaults:
  - scope:
        path: ""
        type: "posts"
    values:
        excerpt: "{{ page.content }} | slice: 0 300"
  - scope:
        path: ""
        type: "qqGroupGuide"
    values:
        layout: markdownreader_bare
