# Site settings
title: 阿良博客
#author: 多人
# author_avatar: 
email: lionsmail1015@gmail.com
description: 个人博客
baseurl: "" # optional
url: "http://fantasylions.github.io"
#twitter_username: foo_bar
github_username: FantasyLions
github_repo: FantasyLions/fantasylions.github.io
google_analytics: UA-65584551-3
disqus: zl.shi-blog

# Build settings
paginate: 10
markdown: kramdown
permalink: pretty
excerpt_separator: "<!-- more -->"

colors:
  UmmaTan: '#cfc096'
  BurtonTowerBeige: '#9b9a6d'
  TheRockGray: '#989c97'
  ObservatoryWhite: '#e4e1df'
  AngellHallAsh: '#a79d96'
  LawQuadStone: '#655a52'
  HillBrown: '#7a121c'
  LSAOrange: '#cc6600'
  ArchwayIvy: '#7e732f'
  RackhamRoofGreen: '#83b2a8'
  CanhamPoolBlue: '#587abc'
  MatthaeiViolet: '#575294'
  Blue: '#003366'

authors:
  zl.shi:
    display_name: zl.shi 
    gravatar: https://www.gravatar.com/avatar/0db85dd6e3b1972fafa2c36e6df3abfb?s=50     
    email: lionsmail1015@gmail.com
    web: http://fantasylions.github.io/
    twitter: https://twitter.com/fantasylions
    github: https://github.com/FantasyLions

gems:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-gist
