# Welcome to Jekyll!
#highlighter: redcarpet
highlighter: rouge
markdown: kramdown
kramdown:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
gems: [jekyll-paginate]
paginate: 7
paginate_path: "page:num"
layout: post
permalink: /:categories/:title
excerpt_separator: "[-----]"

# Site settings
title: 无用郎中
description: 经过多年风与火的洗礼，只要努力没有什么bug是搞不出来的
owner:
  name: zl.shi # or company name
  bio: >
    Interests: programming, Skating, Cycling, science, history.
    Sometimes you'll see me a man riding a bicycle in the city
  disqus_shortname: fantasyLion
  email: lionsmail1015@gmail.com
  url: http://blog.shizhengliang.com
  avatar: owner.png
first_published: 2014 # if migrating another site, the year of your first publish
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://blog.shizhengliang.com" # the base hostname & protocol for your site

# on landing page
greeting: |
  Welcome!  
  I hope you enjoy my blog
features-title: Featured topics
closing-head: Thanks for visiting
closing-para: Feel free to get in touch. Cheers!

# on all pages
social:
  twitter: https://twitter.com/fantasylions
  github: https://github.com/fantasylion
  linkedin-square: https://linkedin.com/in/FantasyLions
  facebook-official: https://www.facebook.com/serio.shi
  google-plus-square: https://plus.google.com/u/0/103035350124326308105/posts
  email: /contact/


# Build settings
#permalink: /:categories/:title.html

#sass:
#  style: compressed
exclude: ['site.bat']
include: ['_pages','.htaccess']
defaults:
  - scope:
      path: _pages
    values:
      layout: page
      #permalink: /:slug/ # see github.com/jekyll/jekyll/issues/2280 for restriction
