highlighter: pygments

markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]

gems: [jekyll-paginate]
paginate: 7
paginate_path: "page:num"
layout: post
permalink: /:categories/:title
excerpt_separator: "[-----]"

# mode: dev
mode: product
url: http://fantasylions.github.io/
devurl: http://localhost:4000/
name: Fantasylion
title: 无用郎中 | 生命不止，奋斗不息
description: "zl.shi's personal weblog, on coding or such stuff"

my:
    displayName: zl.shi
    realName: zl.shi
    realName_cn: 施正良
    jobTitle: "Web Coder"
    contact:
        qq: 473112797
        email: lionsmail1015@gmail.com
        github: https://github.com/FantasyLions
        qzone: http://473112797.qzone.qq.com
        Twiter: https://twitter.com/fantasylions
	Facebook:https://www.facebook.com/zl.shi
        tel: 15671542698
        address:
            country: China
            state: ZheJiang
            city: huzhou
            distribute: Hongshan
            postcode: 450000
    skills:
        frontend: ["HTML | Markdown", "CSS | SASS", "JS | jQuery", "Bootstrap", "Rangular"]
        backend: ["Java", "MySQL", "Redis"]
        tools: ["Sublime Text", "Eclipse", "Git | Github", "Linux", "Jekyll"]

collections:
    qqGroupGuide:
        output: true

defaults:
  - scope:
        path: ""
        type: "posts"
    values:
        excerpt: "{{ page.content }} | slice: 0 300"
  - scope:
        path: ""
        type: "qqGroupGuide"
    values:
        layout: markdownreader_bare
