# Welcome to Jekyll!
#

# Site settings
title: 无用郎中
description: Flowing creativity &#x2192; Cascading bliss
owner:
  name: Gary Faircloth # or company name
  bio: >
    Interests: tech writing, programming, science, history.
    You might also find me playing some PC Ga&mdash;SQUIRREL!
  disqus_shortname: fantasyLion
  email: lionsmail1015@gmail.com
  url: http://blog.shizhengliang.com
  avatar: owner.png
first_published: 1996 # if migrating another site, the year of your first publish
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://blog.shizhengliang.com" # the base hostname & protocol for your site

# on landing page
greeting: |
  Welcome!  
  I hope you enjoy my collection
features-title: Featured topics
closing-head: Thanks for visiting
closing-para: Feel free to get in touch. Cheers!

# on all pages
social:
  twitter: https://twitter.com/fantasylion
  github: https://github.com/FantasyLions
  linkedin-square: https://linkedin.com/in/FantasyLions
  facebook-official: https://facebook.com/zl.shi
  google-plus-square: https://plus.google.com/u/0/+FantasyLions
  email: /contact/
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
permalink: /:categories/:title.html
markdown: kramdown
#sass:
#  style: compressed
exclude: ['site.bat']
include: ['_pages','.htaccess']
defaults:
  - scope:
      path: _pages
    values:
      layout: page
      #permalink: /:slug/ # see github.com/jekyll/jekyll/issues/2280 for restriction
